---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(data.table)
library(here)
library(fs)
source(here("R/functions.R"))
```

## Importing new data

```{r}
#| eval: false
dt <- here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  fread(nrows = 100)
setnames(dt, to_snake_case)

here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


## Exercise: Reading other file

```{r}
#| eval: false

dt <- here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  fread()
setnames(dt, to_snake_case)

dt <- here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  fread(nrows = 100)
setnames(dt, to_snake_case)

dt <- here("data-raw/nurses-stress/stress/6b/6B_1587569373/EDA.csv.gz") |>
  fread()
setnames(dt, to_snake_case)

dt <- here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  fread(nrows = 100)
setnames(dt, to_snake_case)
```

## Making a function to add numbers

```{r}
# Its a roxy - explains the function
#' Add two numbers together
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}

add_numbers(1, 2)
```

## Import 5C's HR data with a function

```{r}
#| eval: false

#' Read in one nurses' stress data file.
#'
#' @param file_path Path to the data file.
#'
#' @returns Outputs a data.table.
#'
read <- function(file_path) {
  dt <- file_path |>
    fread(nrows = 100)
  setnames(dt, to_snake_case)
  return(dt)
}
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```



```{r}
# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(n_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(n_rows = Inf)
```


## Using map

```{r}
hr_files <- here("data-raw/nurses-stress/stress/") |>
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_data <- hr_files |>
  map(read) |>
  list_rbind(names_to = "file_path_id")

hr_data_l <- hr_files |>
  lapply(read) |>
  rbindlist(idcol = "source")
```

## Exercise: Convert map to function and use on sleep

```{r}
#| eval: false

#' Function reading all files within the nurses-stress stress subfolder
#'
#' @param filename Specifies the file type you want to load
#'
#' @returns a data.table
#' @export
#'
#' @examples
read_all <- function(filename, n_rows = 100) {
  files <- here::here("data-raw/nurses-stress/stress/") |>
    fs::dir_ls(regexp = filename, recurse = TRUE)

  data <- files |>
    lapply(\(file) read(file, n_rows = n_rows)) |>
    data.table::rbindlist(idcol = "source")

  return(data)
}
```


## Inspecting the data

```{r}
hr_data <- read_all("HR.csv.gz")

survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read()

hr_data
survey_data
```

## Working with across

```{r}
hr_data <- read_all("HR.csv.gz") |>
  get_participant_id()
```

```{r}
hr_data |> 
  summarise(
    across(
      where(is.numeric),
      list(
        mean = mean,
        median = median,
        sd = sd
      )
    )
  )
```

## Working with dates

```{r}
hr_data |> 
  mutate(datetime = round_date(collection_datetime, unit = "minute"), 
         .before = collection_datetime)

hr_data |> 
  mutate(datetime = date_round(collection_datetime, "minute"))
```

## Summarising by groups

```{r}
hr_data |> 
  mutate(
    collection_datetime = round_date(
      collection_datetime, 
      unit = "minute"
    )
  ) |> 
  summarise(
    across(
      where(is.numeric),
      list(mean = mean, sd = sd, median = median)
    ),
    .by = c(id, collection_datetime)
  )
```








